### Registration
POST localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Rahmatullo",
  "surname": "Odilov",
  "email": "leomessiy103010@gmail.com",
  "password": "123456"

}